services:
  backend:
    image: nongdev/smart-store-backend:latest
    container_name: smart_store_backend
    restart: always
    networks:
      - web
    env_file:
      - ./backend/.env
    volumes:
      - smart_store_backend_storage:/var/www/html/storage
      - ./backend/bootstrap/cache:/var/www/html/bootstrap/cache
    command: >
      sh -c "chown -R www-data:www-data storage bootstrap/cache &&
            chmod -R 775 storage bootstrap/cache &&
            mkdir -p /var/log/supervisor &&
            /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"

  frontend:
    build:
      context: ./frontend
    container_name: smart_store_frontend
    image: nongdev/smart-store-frontend:latest
    restart: always
    networks:
      - web

  webserver:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    image: nongdev/smart-store-webserver:latest
    container_name: smart_store_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "84:84"
    # volumes:
    #   - ./backend/public:/var/www/html/public
    #   - smart_store_backend_storage:/var/www/html/storage
    networks:
      - web
      - internal_project_network
    depends_on:
      - backend

networks:
  web:
    external: true
  internal_project_network:
    driver: bridge

volumes:
  smart_store_backend_storage: