<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\ScopedBy;
use App\Models\Scopes\TenantScope;

#[ScopedBy(TenantScope::class)]
class Menu extends BaseModel
{
    protected $fillable = [
        'tenant_id',
        'name',
        'description',
        'is_default',
        'is_active',
    ];

    protected $casts = [
        'is_default' => 'boolean',
        'is_active'  => 'boolean',
    ];

    // ─── Relationships ────────────────────────────────────────────────────────
    public function tenant()
    {
        return $this->belongsTo(Tenant::class);
    }

    public function branches()
    {
        // ->using(BranchMenu::class) is required, not cosmetic: branch_menus
        // has its own uuid primary key (generated by BaseModel's creating()
        // hook), but sync()/attach() do raw inserts bypassing the model
        // entirely unless the pivot model is registered here — without it,
        // sync() 500s on a not-null violation on branch_menus.id.
        return $this->belongsToMany(Branch::class, 'branch_menus')
            ->using(BranchMenu::class)
            ->withPivot('id', 'available_from', 'available_until', 'days_of_week', 'sort_order');
    }
}
