<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Font;

class OrderExportController extends Controller
{
    /**
     * GET /api/v1/orders/export
     * Downloads an .xlsx file with 3 sheets:
     *   1. Summary  — stats snapshot
     *   2. Orders   — all matched orders
     *   3. Items    — all line items
     */
    public function export(Request $request)
    {
        // ── Build query (same filters as index) ───────────────────────────────
        $orders = Order::with([
            'branch:id,name',
            'customer:id,name,phone,tier',
            'items.product:id,name,sku,barcode',
        ])
            ->when(
                !auth()->user()->is_super_admin,
                fn($q) =>
                $q->where('tenant_id', auth()->user()->resolveTenantId())
            )
            ->when($request->branch_id,    fn($q) => $q->where('branch_id',      $request->branch_id))
            ->when($request->status,       fn($q) => $q->where('status',         $request->status))
            ->when($request->order_type,   fn($q) => $q->where('order_type',     $request->order_type))
            ->when($request->payment_method, fn($q) => $q->where('payment_method', $request->payment_method))
            ->when($request->date_from,    fn($q) => $q->whereDate('created_at', '>=', $request->date_from))
            ->when($request->date_to,      fn($q) => $q->whereDate('created_at', '<=', $request->date_to))
            ->when(
                $request->search,
                fn($q) =>
                $q->where(
                    fn($q2) =>
                    $q2->where('order_number', 'like', "%{$request->search}%")
                        ->orWhereHas(
                            'customer',
                            fn($q3) =>
                            $q3->where('name',  'like', "%{$request->search}%")
                                ->orWhere('phone', 'like', "%{$request->search}%")
                        )
                )
            )
            ->orderBy('created_at', 'desc')
            ->get();

        // ── Stats ─────────────────────────────────────────────────────────────
        $stats = [
            'total_orders'  => $orders->count(),
            'total_revenue' => $orders->where('status', '!=', 'cancelled')->sum('total_amount'),
            'completed'     => $orders->where('status', 'completed')->count(),
            'pending'       => $orders->where('status', 'pending')->count(),
            'cancelled'     => $orders->where('status', 'cancelled')->count(),
        ];

        // ── Build spreadsheet ─────────────────────────────────────────────────
        $spreadsheet = new Spreadsheet();
        $spreadsheet->getProperties()
            ->setTitle('Order Report')
            ->setCreator('BrewDesk')
            ->setDescription('Generated by BrewDesk POS');

        // ── Sheet 1: Summary ──────────────────────────────────────────────────
        $this->buildSummarySheet($spreadsheet->getActiveSheet(), $stats, $request);

        // ── Sheet 2: Orders ───────────────────────────────────────────────────
        $ordersSheet = $spreadsheet->createSheet();
        $this->buildOrdersSheet($ordersSheet, $orders);

        // ── Sheet 3: Order Items ──────────────────────────────────────────────
        $itemsSheet = $spreadsheet->createSheet();
        $this->buildItemsSheet($itemsSheet, $orders);

        $spreadsheet->setActiveSheetIndex(0);

        // ── Stream download ───────────────────────────────────────────────────
        $filename = 'Order-Report-' . now()->format('Y-m-d') . '.xlsx';

        $writer = new Xlsx($spreadsheet);

        return response()->streamDownload(function () use ($writer) {
            $writer->save('php://output');
        }, $filename, [
            'Content-Type'        => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Cache-Control'       => 'max-age=0',
            'Content-Disposition' => 'attachment',
        ]);
    }

    // ── Sheet builders ─────────────────────────────────────────────────────────

    private function buildSummarySheet($sheet, array $stats, Request $request): void
    {
        $sheet->setTitle('Summary');

        // Title
        $sheet->setCellValue('A1', 'Order Report — Summary');
        $sheet->mergeCells('A1:C1');
        $sheet->getStyle('A1')->applyFromArray([
            'font'      => ['bold' => true, 'size' => 14, 'color' => ['argb' => 'FF1A5276']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT],
        ]);

        // Generated at
        $sheet->setCellValue('A2', 'Generated: ' . now()->format('d M Y H:i'));
        $sheet->getStyle('A2')->applyFromArray([
            'font' => ['italic' => true, 'color' => ['argb' => 'FF666666']],
        ]);

        // Filters applied
        $sheet->setCellValue('A3', 'Filters:');
        $filterStr = collect([
            $request->date_from   ? 'From: ' . $request->date_from     : null,
            $request->date_to     ? 'To: '   . $request->date_to       : null,
            $request->status      ? 'Status: ' . $request->status      : null,
            $request->order_type  ? 'Type: '   . $request->order_type  : null,
        ])->filter()->join(' | ') ?: 'All orders';
        $sheet->setCellValue('B3', $filterStr);

        // Stats header
        $sheet->setCellValue('A5', 'Metric');
        $sheet->setCellValue('B5', 'Value');
        $this->applyHeaderStyle($sheet, 'A5:B5');

        // Stats rows
        $statsData = [
            ['Total Orders',   $stats['total_orders']],
            ['Total Revenue',  number_format($stats['total_revenue'], 2)],
            ['Completed',      $stats['completed']],
            ['Pending',        $stats['pending']],
            ['Cancelled',      $stats['cancelled']],
        ];

        $row = 6;
        foreach ($statsData as $i => [$label, $value]) {
            $sheet->setCellValue("A{$row}", $label);
            $sheet->setCellValue("B{$row}", $value);
            if ($i % 2 === 0) {
                $sheet->getStyle("A{$row}:B{$row}")->applyFromArray([
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'color' => ['argb' => 'FFF2F3F4']],
                ]);
            }
            $row++;
        }

        $sheet->getColumnDimension('A')->setWidth(22);
        $sheet->getColumnDimension('B')->setWidth(22);
        $sheet->getColumnDimension('C')->setWidth(30);
    }

    private function buildOrdersSheet($sheet, $orders): void
    {
        $sheet->setTitle('Orders');

        $headers = [
            'Order #',
            'Branch',
            'Customer',
            'Phone',
            'Tier',
            'Type',
            'Items',
            'Subtotal',
            'Discount',
            'Tax',
            'Service Charge',
            'Total',
            'Payment',
            'Status',
            'Date',
            'Time',
        ];

        // Header row
        foreach ($headers as $col => $header) {
            $cell = $this->colLetter($col) . '1';
            $sheet->setCellValue($cell, $header);
        }
        $this->applyHeaderStyle($sheet, 'A1:' . $this->colLetter(count($headers) - 1) . '1');

        // Data rows
        $row = 2;
        foreach ($orders as $i => $order) {
            $bg = $i % 2 === 0 ? 'FFFFFFFF' : 'FFF8F9FA';
            $data = [
                $order->order_number,
                $order->branch?->name ?? '',
                $order->customer?->name ?? 'Walk-in',
                $order->customer?->phone ?? '',
                $order->customer?->tier ?? 'regular',
                $order->order_type ?? '',
                $order->items->count(),
                (float) ($order->subtotal ?? 0),
                (float) ($order->discount_amount ?? 0),
                (float) ($order->tax_amount ?? 0),
                (float) ($order->service_charge ?? 0),
                (float) ($order->total_amount ?? 0),
                $order->payment_method ?? '',
                $order->status,
                $order->created_at?->format('d M Y') ?? '',
                $order->created_at?->format('H:i') ?? '',
            ];

            foreach ($data as $col => $value) {
                $cell = $this->colLetter($col) . $row;
                $sheet->setCellValue($cell, $value);
            }

            // Zebra stripe
            $sheet->getStyle("A{$row}:" . $this->colLetter(count($headers) - 1) . $row)
                ->applyFromArray([
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'color' => ['argb' => $bg]],
                ]);

            // Color status cell
            $statusCol = $this->colLetter(13) . $row; // Status column
            $statusColor = match ($order->status) {
                'completed' => 'FF1E8449',
                'cancelled' => 'FFC0392B',
                'pending'   => 'FFD68910',
                default     => 'FF2C3E50',
            };
            $sheet->getStyle($statusCol)->applyFromArray([
                'font' => ['color' => ['argb' => $statusColor], 'bold' => true],
            ]);

            $row++;
        }

        // Column widths
        $widths = [16, 20, 20, 14, 10, 12, 8, 12, 10, 10, 14, 12, 14, 12, 14, 10];
        foreach ($widths as $col => $width) {
            $sheet->getColumnDimension($this->colLetter($col))->setWidth($width);
        }

        // Freeze header row
        $sheet->freezePane('A2');

        // Auto-filter
        $sheet->setAutoFilter('A1:' . $this->colLetter(count($headers) - 1) . '1');
    }

    private function buildItemsSheet($sheet, $orders): void
    {
        $sheet->setTitle('Order Items');

        $headers = [
            'Order #',
            'Branch',
            'Date',
            'Product',
            'SKU',
            'Barcode',
            'Qty',
            'Unit Price',
            'Discount',
            'Total',
            'Note',
        ];

        foreach ($headers as $col => $header) {
            $sheet->setCellValue($this->colLetter($col) . '1', $header);
        }
        $this->applyHeaderStyle($sheet, 'A1:' . $this->colLetter(count($headers) - 1) . '1');

        $row = 2;
        $i   = 0;
        foreach ($orders as $order) {
            foreach ($order->items as $item) {
                $bg   = $i % 2 === 0 ? 'FFFFFFFF' : 'FFF8F9FA';
                $data = [
                    $order->order_number,
                    $order->branch?->name ?? '',
                    $order->created_at?->format('d M Y') ?? '',
                    $item->product?->name ?? $item->name ?? '',
                    $item->product?->sku ?? '',
                    $item->product?->barcode ?? '',
                    (int) $item->quantity,
                    (float) ($item->price ?? 0),
                    (float) ($item->discount_amount ?? 0),
                    (float) (($item->price ?? 0) * $item->quantity),
                    $item->note ?? '',
                ];

                foreach ($data as $col => $value) {
                    $sheet->setCellValue($this->colLetter($col) . $row, $value);
                }

                $sheet->getStyle("A{$row}:" . $this->colLetter(count($headers) - 1) . $row)
                    ->applyFromArray([
                        'fill' => ['fillType' => Fill::FILL_SOLID, 'color' => ['argb' => $bg]],
                    ]);

                $row++;
                $i++;
            }
        }

        $widths = [16, 18, 12, 24, 12, 14, 6, 12, 10, 12, 24];
        foreach ($widths as $col => $width) {
            $sheet->getColumnDimension($this->colLetter($col))->setWidth($width);
        }

        $sheet->freezePane('A2');
        $sheet->setAutoFilter('A1:' . $this->colLetter(count($headers) - 1) . '1');
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    private function applyHeaderStyle($sheet, string $range): void
    {
        $sheet->getStyle($range)->applyFromArray([
            'font' => [
                'bold'  => true,
                'color' => ['argb' => 'FFFFFFFF'],
                'name'  => 'Arial',
                'size'  => 11,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'color'    => ['argb' => 'FF1A5276'],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_LEFT,
                'vertical'   => Alignment::VERTICAL_CENTER,
            ],
        ]);
    }

    private function colLetter(int $index): string
    {
        // 0=A, 1=B, 25=Z, 26=AA ...
        $letters = '';
        $index++;
        while ($index > 0) {
            $index--;
            $letters = chr(65 + ($index % 26)) . $letters;
            $index   = (int) ($index / 26);
        }
        return $letters;
    }
}
