<template>
  <v-dialog v-model="model" max-width="580" persistent>
    <v-card rounded="xl">
      <v-card-title>
        <div class="d-flex align-center justify-space-between">
          <div>
            {{ isEdit ? 'Edit' : 'New' }}
            {{ isStaff ? 'Staff Member' : 'Shift' }}
          </div>
          <v-btn icon="mdi-close" variant="text" color="grey" @click="close" />
        </div>
      </v-card-title>

      <v-divider />

      <v-card-text class="pa-6">
        <v-form ref="formRef">
          <!-- ══ STAFF FORM ══════════════════════════════════════════════════ -->
          <template v-if="isStaff">
            <div class="text-overline mb-2 text-primary">Identity</div>
            <v-row dense>
              <!-- Tenant — required to filter branches -->
              <v-col cols="12">
                <v-select
                  v-model="form.tenant_id"
                  :items="tenants"
                  item-value="id"
                  item-title="name"
                  label="Tenant (Business)"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  :rules="[r.required]"
                  prepend-inner-icon="mdi-domain"
                  @update:modelValue="onTenantChange"
                />
              </v-col>

              <!-- User -->
              <v-col cols="12" sm="6">
                <v-select
                  v-model="form.user_id"
                  :items="users.data || users"
                  item-value="id"
                  item-title="full_name"
                  label="User"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  :rules="[r.required]"
                  prepend-inner-icon="mdi-account-outline"
                >
                  <!-- Show full name + email in dropdown -->
                  <template #item="{ props, item }">
                    <v-list-item v-bind="props" :subtitle="item.raw?.email" />
                  </template>
                </v-select>
              </v-col>

              <!-- Employee Code -->
              <v-col cols="12" sm="6">
                <v-text-field
                  v-model="form.employee_code"
                  label="Employee Code"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  prepend-inner-icon="mdi-identifier"
                  :readonly="!editingCode"
                  :bg-color="!editingCode ? 'grey-lighten-4' : undefined"
                  hint="Auto-generated by system"
                  persistent-hint
                >
                  <template #append-inner>
                    <!-- Lock icon = locked, click to unlock -->
                    <v-tooltip
                      :text="editingCode ? 'Lock code' : 'Edit manually'"
                    >
                      <template #activator="{ props }">
                        <v-icon
                          v-bind="props"
                          :icon="
                            editingCode
                              ? 'mdi-lock-open-outline'
                              : 'mdi-lock-outline'
                          "
                          size="18"
                          class="cursor-pointer text-medium-emphasis"
                          @click="toggleEditCode"
                        />
                      </template>
                    </v-tooltip>
                  </template>
                </v-text-field>
              </v-col>

              <!-- Role -->
              <v-col cols="12" sm="6">
                <v-select
                  v-model="form.role_id"
                  label="Role"
                  variant="outlined"
                  density="comfortable"
                  :items="filteredRoles"
                  item-title="name"
                  item-value="id"
                  rounded="lg"
                  :rules="[r.required]"
                  prepend-inner-icon="mdi-shield-account-outline"
                  :disabled="!form.tenant_id"
                  :hint="!form.tenant_id ? 'Select a tenant first' : ''"
                  persistent-hint
                />
              </v-col>

              <!-- Branch — filtered by tenant -->
              <v-col cols="12" sm="6">
                <v-select
                  v-model="form.branch_id"
                  :items="filteredBranches"
                  item-value="id"
                  item-title="name"
                  label="Branch"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  :rules="[r.required]"
                  prepend-inner-icon="mdi-store-outline"
                  :disabled="!form.tenant_id"
                  :hint="!form.tenant_id ? 'Select a tenant first' : ''"
                  persistent-hint
                  :loading="loadingBranches"
                >
                  <template #item="{ props, item }">
                    <v-list-item
                      v-bind="props"
                      :subtitle="item.raw?.city || ''"
                    />
                  </template>
                </v-select>
              </v-col>
            </v-row>

            <div class="text-overline mb-2 mt-4 text-primary">Employment</div>
            <v-row dense>
              <!-- Hire Date -->
              <v-col cols="12" sm="6">
                <v-text-field
                  v-model="form.hire_date"
                  type="date"
                  label="Hire Date"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                />
              </v-col>

              <!-- Hourly Rate -->
              <v-col cols="12" sm="6">
                <v-text-field
                  v-model.number="form.hourly_rate"
                  type="number"
                  label="Hourly Rate ($)"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  min="0"
                  prepend-inner-icon="mdi-currency-usd"
                />
              </v-col>

              <!-- PIN Code — FIX: added length validation -->
              <v-col cols="12" sm="6">
                <v-text-field
                  v-model="form.pin_code"
                  label="PIN Code (4–6 digits)"
                  :type="showPin ? 'text' : 'password'"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  :append-inner-icon="showPin ? 'mdi-eye-off' : 'mdi-eye'"
                  :rules="[r.pin]"
                  maxlength="6"
                  hint="4 to 6 digits only"
                  persistent-hint
                  @click:append-inner="showPin = !showPin"
                />
              </v-col>

              <!-- Active Status -->
              <v-col cols="12" sm="6" class="d-flex align-center">
                <v-switch
                  v-model="form.is_active"
                  label="Active Status"
                  color="success"
                  inset
                />
              </v-col>
            </v-row>
          </template>

          <!-- ══ SHIFT FORM ══════════════════════════════════════════════════ -->
          <template v-else>
            <v-row dense>
              <!-- FIX: staff_id is now a dropdown not a plain text field -->
              <v-col cols="12" sm="6">
                <v-select
                  v-model="form.staff_id"
                  :items="staffList"
                  item-value="id"
                  item-title="user.full_name"
                  label="Staff Member"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  :rules="[r.required]"
                  prepend-inner-icon="mdi-account-outline"
                  :loading="loadingStaff"
                >
                  <template #item="{ props, item }">
                    <v-list-item
                      v-bind="props"
                      :subtitle="item.raw?.role?.name || ''"
                    />
                  </template>
                </v-select>
              </v-col>

              <!-- FIX: branch_id is now a dropdown not a plain text field -->
              <v-col cols="12" sm="6">
                <v-select
                  v-model="form.branch_id"
                  :items="filteredBranches"
                  item-value="id"
                  item-title="name"
                  label="Branch"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  :rules="[r.required]"
                  prepend-inner-icon="mdi-store-outline"
                />
              </v-col>

              <!-- Scheduled Start -->
              <v-col cols="12" sm="6">
                <v-text-field
                  ref="scheduledStartRef"
                  v-model="form.scheduled_start"
                  type="datetime-local"
                  label="Scheduled Start"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  :rules="[r.required]"
                />
              </v-col>

              <!-- Scheduled End — must be after start -->
              <v-col cols="12" sm="6">
                <v-text-field
                  ref="scheduledEndRef"
                  v-model="form.scheduled_end"
                  type="datetime-local"
                  label="Scheduled End"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  :rules="[r.required, r.afterStart]"
                />
              </v-col>

              <!-- Notes -->
              <v-col cols="12">
                <v-textarea
                  v-model="form.notes"
                  label="Notes"
                  variant="outlined"
                  density="comfortable"
                  rounded="lg"
                  rows="2"
                />
              </v-col>
            </v-row>
          </template>
        </v-form>
      </v-card-text>

      <v-divider />
      <v-card-actions>
        <v-spacer />
        <v-btn variant="tonal" rounded="lg" @click="close">Cancel</v-btn>
        <v-btn
          color="primary"
          variant="flat"
          rounded="lg"
          :loading="loading"
          @click="submit"
        >
          {{ isEdit ? 'Save Changes' : 'Create' }}
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script setup>
  import { ref, reactive, computed, watch, onMounted } from 'vue'
  import { storeToRefs } from 'pinia'
  import { useUserStore } from '@/stores/userStore'
  import { useRoleStore } from '@/stores/roleStore'
  import { useBranchStore } from '@/stores/branchStore'
  import { useStaffStore } from '@/stores/staffStore'
  import { useTenantStore } from '@/stores/tenantStore'

  // ── Props & Emits ─────────────────────────────────────────────────────────────
  const props = defineProps({
    modelValue: Boolean,
    mode: String, // 'staff' or 'shifts'
    item: Object,
    loading: Boolean
  })

  const emit = defineEmits(['update:modelValue', 'save'])

  // ── Stores ────────────────────────────────────────────────────────────────────
  const userStore = useUserStore()
  const roleStore = useRoleStore()
  const branchStore = useBranchStore()
  const staffStore = useStaffStore()
  const tenantStore = useTenantStore()

  const { users } = storeToRefs(userStore)
  const { roles } = storeToRefs(roleStore)
  const { branches } = storeToRefs(branchStore)
  const { tenants } = storeToRefs(tenantStore)

  // ── Local state ───────────────────────────────────────────────────────────────
  const formRef = ref(null)
  const scheduledStartRef = ref(null)
  const scheduledEndRef = ref(null)
  const showPin = ref(false)
  const loadingBranches = ref(false)
  const loadingStaff = ref(false)
  const staffList = ref([])

  // ── v-model dialog ────────────────────────────────────────────────────────────
  const model = computed({
    get: () => props.modelValue,
    set: val => emit('update:modelValue', val)
  })

  const isEdit = computed(() => !!props.item?.id)
  const isStaff = computed(() => props.mode === 'staff')

  const editingCode = ref(false)
  const toggleEditCode = () => {
    editingCode.value = !editingCode.value
    if (!editingCode.value) {
      // User locked it back — clear their input so BE generates it
      form.employee_code = ''
    }
  }
  // ── Branches filtered by selected tenant ──────────────────────────────────────
  // This is the KEY FIX — only show branches belonging to the selected tenant
  const filteredBranches = computed(() => {
    if (!form.tenant_id) return []
    const allBranches = branches.value?.data || branches.value || []
    return allBranches.filter(b => b.tenant_id === form.tenant_id)
  })

  // ── Roles filtered by selected tenant ────────────────────────────────────────
  const filteredRoles = computed(() => {
    if (!form.tenant_id) return []
    const allRoles = roles.value?.data || roles.value || []
    // Roles can be system-wide (no tenant_id) or tenant-specific
    return allRoles.filter(r => !r.tenant_id || r.tenant_id === form.tenant_id)
  })

  // ── When tenant changes — reset branch/role and reload staff ──────────────────
  const onTenantChange = async tenantId => {
    form.branch_id = null
    form.role_id = null

    if (!tenantId) return

    // Reload staff filtered by tenant (for shift dropdown)
    loadingStaff.value = true
    try {
      const res = await staffStore.fetchStaff({ tenant_id: tenantId })
      staffList.value = res?.data || staffStore.staffList || []
    } finally {
      loadingStaff.value = false
    }
  }

  // ── Validation rules ──────────────────────────────────────────────────────────
  const r = {
    required: v => !!v || 'This field is required',

    // PIN: optional but if filled must be 4-6 digits only
    pin: v => {
      if (!v) return true
      if (!/^\d{4,6}$/.test(v)) return 'PIN must be 4 to 6 digits'
      return true
    },

    // Shift end must be after start
    afterStart: v => {
      if (!v || !form.scheduled_start) return true
      return (
        new Date(v) > new Date(form.scheduled_start) ||
        'Must be after scheduled start'
      )
    }
  }

  // ── Form state ────────────────────────────────────────────────────────────────
  const form = reactive({})

  watch(
    () => props.item,
    val => {
      Object.keys(form).forEach(k => delete form[k])
      editingCode.value = false
      if (val) {
        Object.assign(form, val)
        form.employee_code = ''
      } else {
        Object.assign(
          form,
          isStaff.value ? { is_active: true, hourly_rate: 0 } : {}
        )
      }
    },
    { immediate: true }
  )

  // Cross-validate shift end when start changes
  watch(
    () => form.scheduled_start,
    () => scheduledEndRef.value?.validate()
  )

  // ── Actions ───────────────────────────────────────────────────────────────────
  const close = () => {
    model.value = false
  }

  const submit = async () => {
    const { valid } = await formRef.value.validate()
    if (valid) emit('save', { ...form })
  }

  // ── Load initial data ─────────────────────────────────────────────────────────
  onMounted(async () => {
    await Promise.all([
      tenantStore.fetchTenants(),
      branchStore.fetchBranches(), // load ALL branches, filter in computed
      roleStore.fetchRoles(),
      userStore.fetchUsers()
    ])
  })
</script>
